version: "3"

services:

  mysql:
    image: mysql:8
    container_name: incident-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: incidents_db
      MYSQL_USER: incidentuser
      MYSQL_PASSWORD: incidentpass
    ports:
      - "3306:3306"

  app:
    image: jayneeshk/incident-app:latest
    container_name: incident-app
    restart: always
    ports:
      - "80:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: incidentuser
      DB_PASSWORD: incidentpass
      DB_NAME: incidents_db