apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_HOST: "incidentdb.cveismqi63r3.eu-north-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USER: "admin"
  DB_PASSWORD: "Admin1234!"
  DB_NAME: "incidentdb"